const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.join(__dirname,'..');const game=fs.readFileSync(path.join(root,'public','game.js'),'utf8');const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');const pkg=require(path.join(root,'package.json'));
let passed=0;function test(n,f){try{f();console.log('PASS',n);passed++;}catch(e){console.error('FAIL',n);console.error(e.stack||e);process.exitCode=1;}}
test('package is v1.17.0',()=>assert.equal(pkg.version,'1.17.0'));
test('old fantasy display names are gone from live game code',()=>{for(const s of ['마법미사일','축소 광선','마도사의 주스 상자','감시의 장막','검을 뽑아라','지옥의 전도체','탄환 세례'])assert(!game.includes(s),s);});
test('new seven themed treasure names are present',()=>{for(const s of ['자동 급식기','쪼그라들개!','간식 냠냠','넥카라 철벽','발톱 슥삭','산책줄 휘리릭','발바닥 도장'])assert(game.includes(s),s);});
test('v1.16.2 hitbox and grape target lock safeguards remain',()=>{for(const s of ["gamja: { src: '/assets/players/gamja.png'","hitbox: { r: 6, cx: 33, cy: 50 }","raid:  { visualRadius:8, hitRadius:5.5 }","enemy.rushTargetX=t.x;enemy.rushTargetY=t.y","phase2Overshoot: 60"])assert(game.includes(s),s);});
test('grape warning is a thick floor corridor with no arrowhead texture',()=>{assert(game.includes("create('rushLine', 128, 24"));assert(game.includes('실제 돌진 폭'));const rushBlock=game.slice(game.indexOf("create('rushLine'"),game.indexOf("create('snackNibble'"));assert(!rushBlock.includes('fillTriangle('));});
test('skill choice cards expose upgradeSummary hierarchy',()=>{assert(game.includes('upgradeSummary:treasureSkillUpgradeSummary'));assert(game.includes('upgradeSummary:majorAugmentUpgradeSummary'));assert(css.includes('choice-upgrade')||html.includes('choice-upgrade')||game.includes('choice-upgrade'));});
test('2P architecture, revive and pending boss protections remain',()=>{for(const s of ['pendingTrueBoss','reviveProgress','reviveNeedMs','coopSnapshot','coopInput','volatile','networkRole','buildNetworkSnapshot'])assert(game.includes(s)||html.includes(s)||css.includes(s),s);});
test('persistent skill objects are explicitly bounded',()=>{for(const s of ['while(this.gasClouds.length>18)','while(this.territoryZones.length>7)','while(this.raidHazards.length>6)','while((this.pawMines||[]).length>=st.maxMines)'])assert(game.includes(s),s);});
test('themed TRUE boss projectile graphics retain raid collision core',()=>{for(const s of ['raidGrapeBullet','raidChocoBullet','raidOnionPeel','raidOnionRing'])assert(game.includes(s));assert(game.includes("b.hitRadius=hit.hitRadius"));assert(game.includes("b.body.setCircle(hit.hitRadius"));});
test('network sync sends only persistent state extras rather than every cosmetic particle',()=>{for(const s of ['feeder-${b.id}-${i}','leash-${b.id}-${i}','paw-${b.id}-${i}','raidHazard-${i}'])assert(game.includes(s),s);assert(!game.includes('snackNibble-${'));});
test('UI still preserves v1.16 HUD/pause/sound surfaces',()=>{for(const id of ['combat-hud','pause-screen','audio-toggle-btn','levelup-screen','chest-screen'])assert(html.includes(`id="${id}"`),id);});
if(process.exitCode)process.exit(process.exitCode);console.log(`ALL PASS (${passed})`);
