const fs=require('fs');
const path=require('path');
const vm=require('vm');
const assert=require('assert');

const gamePath=path.join(__dirname,'..','public','game.js');
let src=fs.readFileSync(gamePath,'utf8');
src=src.replace(/\}\)\(\);\s*$/,`window.__V17={SurvivorScene,SKILLS,MAJOR_AUGMENTS,TRUE_BOSS_PATTERNS,GRAPE_RUSH,ENEMY_BULLET_HITBOX,PLAYER_SPRITES,treasureSkillStats,treasureSkillUpgradeSummary,majorAugmentUpgradeSummary,treasureSkillDescription,majorAugmentDescription};})();`);
class FakeEl{constructor(){this.classList={add(){},remove(){},toggle(){}};this.style={};this.dataset={};this.value='';this.textContent='';this.innerHTML='';}addEventListener(){}querySelector(){return new FakeEl()}appendChild(){}setAttribute(){}}
class FakeAudio{constructor(){this.volume=1;this.currentTime=0;}addEventListener(){}play(){return Promise.resolve()}pause(){}}
class FakeImage{set src(v){}}
class Scene{constructor(){}}
const PMath={Clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),Between:(a,b)=>Math.floor((a+b)/2),FloatBetween:(a,b)=>(a+b)/2,Distance:{Between:(x1,y1,x2,y2)=>Math.hypot(x2-x1,y2-y1),Squared:(x1,y1,x2,y2)=>{const dx=x2-x1,dy=y2-y1;return dx*dx+dy*dy;}},Angle:{Between:(x1,y1,x2,y2)=>Math.atan2(y2-y1,x2-x1),Wrap:a=>{while(a<=-Math.PI)a+=Math.PI*2;while(a>Math.PI)a-=Math.PI*2;return a;}},Linear:(a,b,t)=>a+(b-a)*t,RadToDeg:r=>r*180/Math.PI};
const context={console,window:{io:null},document:{querySelector:()=>new FakeEl(),querySelectorAll:()=>[],createElement:()=>new FakeEl()},navigator:{clipboard:{writeText:async()=>{}}},localStorage:{getItem:()=>null,setItem(){}},Audio:FakeAudio,Image:FakeImage,Phaser:{Scene,Math:PMath,Utils:{Array:{GetRandom:a=>a[0]}},Scale:{FIT:1,CENTER_BOTH:1},AUTO:1,Game:class{}},setTimeout,clearTimeout,Map,Set,Math,Number,Infinity};
vm.createContext(context);vm.runInContext(src,context,{filename:'game.js'});
const E=context.window.__V17;
let passed=0;function test(n,f){try{f();console.log('PASS',n);passed++;}catch(e){console.error('FAIL',n);console.error(e.stack||e);process.exitCode=1;}}
const treasureIds=['magicMissile','shrinkRay','juiceBox','veil','sword','hellConductor','bulletBarrage'];
const expectedTitles=['자동 급식기','쪼그라들개!','간식 냠냠','넥카라 철벽','발톱 슥삭','산책줄 휘리릭','발바닥 도장'];

function scene(){const s=new E.SurvivorScene();s.init({character:'jjigae'});s.showBanner=()=>{};s.updateHud=()=>{};return s;}

test('treasure pool is exactly seven themed skills',()=>{assert.equal(E.SKILLS.length,7);assert.deepEqual(E.SKILLS.map(x=>x.title),expectedTitles);assert.deepEqual(E.SKILLS.map(x=>x.id),treasureIds);});
test('every treasure skill changes at every level 1 through 5',()=>{for(const id of treasureIds){let prev=null;const summaries=[];for(let lv=1;lv<=5;lv++){const st=E.treasureSkillStats(id,lv);for(const [k,v] of Object.entries(st))if(typeof v==='number')assert(Number.isFinite(v),`${id} Lv${lv} ${k}`);if(prev)assert.notDeepEqual(JSON.parse(JSON.stringify(st)),JSON.parse(JSON.stringify(prev)),`${id} Lv${lv} did not change`);prev=st;summaries.push(E.treasureSkillUpgradeSummary(id,lv));}assert.equal(new Set(summaries).size,5,`${id} summaries`);summaries.forEach(x=>assert(x&&x.length>=5));}});
test('auto feeder growth unlocks size speed multishot pierce frenzy',()=>{const a=[1,2,3,4,5].map(l=>E.treasureSkillStats('magicMissile',l));assert(a[1].pelletScale>a[0].pelletScale&&a[1].shotInterval<a[0].shotInterval);assert.equal(a[2].shots,2);assert.equal(a[3].pierce,1);assert.equal(a[4].frenzy,true);});
test('shrink skill adds slow vulnerability then spread',()=>{const a=[1,2,3,4,5].map(l=>E.treasureSkillStats('shrinkRay',l));assert(a[1].minScale<a[0].minScale);assert(a[2].slowMult<1);assert(a[3].vulnerableMult>1);assert(a[4].spreadRadius>0);});
test('snack skill becomes faster stronger and ends in snack party',()=>{const a=[1,2,3,4,5].map(l=>E.treasureSkillStats('juiceBox',l));assert(a[1].threshold<a[0].threshold);assert(a[2].healPct>a[1].healPct);assert(a[3].speedMult>1);assert(a[4].partyCount>1&&a[4].healPct>a[3].healPct);});
test('collar, claw, leash and paw-stamp unlock distinct mechanics',()=>{const shield=E.treasureSkillStats('veil',5),claw=E.treasureSkillStats('sword',5),leash=E.treasureSkillStats('hellConductor',5),paw=E.treasureSkillStats('bulletBarrage',5);assert.equal(shield.maxCharges,2);assert(shield.clearNormalBullets);assert.equal(claw.directions,8);assert(claw.clearNormalBullets&&claw.finisher);assert.equal(leash.count,2);assert(leash.outerRadius>leash.radius&&leash.bigSwingInterval>0);assert.equal(paw.spawnCount,2);assert(paw.chain&&paw.rapidBurst);});
test('all seven Lv10 augments expose five distinct upgrade summaries',()=>{assert.equal(E.MAJOR_AUGMENTS.length,7);for(const a of E.MAJOR_AUGMENTS){const s=[1,2,3,4,5].map(l=>E.majorAugmentUpgradeSummary(a.id,l));assert.equal(new Set(s).size,5,a.id);s.forEach(x=>assert(x&&x.length>=4));}});
test('boss identities have at least three patterns per phase and required signature mechanics',()=>{for(const kind of ['grape','choco','onion'])for(const phase of [1,2])assert(E.TRUE_BOSS_PATTERNS[kind].filter(p=>p.phase===phase).length>=3,`${kind} p${phase}`);const ids=k=>new Set(E.TRUE_BOSS_PATTERNS[k].map(p=>p.id));assert(ids('grape').has('grapeClusterSplit')&&ids('grape').has('grapeDashBurst'));assert(ids('choco').has('chocoBarSplit')&&ids('choco').has('chocoMelt')&&ids('choco').has('chocoBounce'));assert(ids('onion').has('onionPeelSpiral')&&ids('onion').has('onionRingGap')&&ids('onion').has('onionLayered'));});
test('grape dash keeps target lock but is slower and more readable than v1.16.2',()=>{assert(E.GRAPE_RUSH.targetSpeed>=1250&&E.GRAPE_RUSH.targetSpeed<=1400);assert(E.GRAPE_RUSH.telegraphMs>=750&&E.GRAPE_RUSH.telegraphMs<=850);assert(E.GRAPE_RUSH.phase2TelegraphMs>=720&&E.GRAPE_RUSH.phase2TelegraphMs<=850);assert(E.GRAPE_RUSH.recoveryMs>=550&&E.GRAPE_RUSH.recoveryMs<=700);assert(E.GRAPE_RUSH.overshoot>=45&&E.GRAPE_RUSH.phase2Overshoot>=E.GRAPE_RUSH.overshoot);});
test('v1.16.2 collision honesty remains unchanged',()=>{assert.equal(E.ENEMY_BULLET_HITBOX.raid.hitRadius,5.5);assert.equal(E.ENEMY_BULLET_HITBOX.boss.hitRadius,5);assert.equal(E.ENEMY_BULLET_HITBOX.enemy.hitRadius,3.5);assert.equal(E.PLAYER_SPRITES.gamja.hitbox.r,6);assert.equal(E.PLAYER_SPRITES.jjigae.hitbox.r,7);});
test('juice-box legacy multishot limiter is now snack-gauge diminishing charge',()=>{const s=scene();s.player={x:10,y:10,active:true};s.skillLevels={juiceBox:1};s.runTimeMs=1000;s.snackGauge=0;s.juiceComboHits=0;s.juiceComboUntil=0;s.ensureSnackGaugeVisual=()=>{};let procs=0;s.triggerSnackNibble=()=>{procs++};for(let i=0;i<8;i++)s.chargeSnackOnHit({x:10,y:10},1);assert(s.snackGauge<8,'repeat hits should not charge at full rate');assert.equal(procs,0);s.runTimeMs+=300;s.juiceComboUntil=0;for(let i=0;i<8;i++){s.runTimeMs+=300;s.chargeSnackOnHit({x:10,y:10},1);}assert(procs>=1,'separated hits should eventually proc');});
test('2P build summary preserves individual treasure/major levels and snack state',()=>{const s=scene();s.runTimeMs=10000;const b={id:'p2',characterKey:'gucci',hp:70,maxHp:100,down:false,attackPower:24,moveSpeed:195,basicCooldown:1400,extraBasicShots:1,basicDamageMult:1.05,xpGainMult:1,gemMagnetRange:135,playerDamageMult:1,levelUpgradeCounts:{},augments:[],characterAugmentLevels:{sheddingSeason:1},majorLevels:{poopOrbit:3},skillLevels:{magicMissile:5,sword:4},shieldCharges:0,snackGauge:4,snackSpeedUntil:11500,reviveProgress:0,reviveNeedMs:4800,deathCount:0,playerInvulnUntil:0};const out=s.buildSummary(b);assert.equal(out.skillLevels.magicMissile,5);assert.equal(out.skillLevels.sword,4);assert.equal(out.majorLevels.poopOrbit,3);assert.equal(out.snackGauge,4);assert.equal(out.snackSpeedLeft,1500);});
test('source has themed boss bullets, persistent caps and compact extra syncing',()=>{const source=fs.readFileSync(gamePath,'utf8');for(const key of ['raidGrapeBullet','raidGrapeCluster','raidChocoBullet','raidChocoBig','raidOnionPeel','raidOnionRing','chocoPuddle'])assert(source.includes(key),key);assert(source.includes('while(this.raidHazards.length>6)'));assert(source.includes('while(this.gasClouds.length>18)'));for(const k of ['feeders','leashOrbiters','pawMines','raidHazards'])assert(source.includes(k),k);assert(source.includes('volatile'));});
test('chocolate bounce has a guaranteed one-time mid-arena direction change',()=>{const source=fs.readFileSync(gamePath,'utf8');assert(source.includes('b.bounceAt=this.runTimeMs+700'));assert(source.includes('p.bounceTurn||0.72'));assert(source.includes('p.bounceCount>=1'));});

if(process.exitCode)process.exit(process.exitCode);
console.log(`ALL PASS (${passed})`);
