const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const gamePath=path.join(__dirname,'..','public','game.js');
let src=fs.readFileSync(gamePath,'utf8');
src=src.replace(/\}\)\(\);\s*$/,`window.__TEST_EXPORTS={SurvivorScene,TRUE_BOSS_PATTERNS,TRUE_BOSS_SCHEDULE_MS,TRUE_BOSS_ORDER,BOSS_DEFINITIONS,DELIVERY,HEALING,treasureSkillStats,PLAYER_SPRITES,ENEMY_BULLET_HITBOX,GRAPE_RUSH};})();`);
class FakeEl{constructor(){this.classList={add(){},remove(){},toggle(){}};this.style={};this.dataset={};this.value='';this.textContent='';this.innerHTML='';this.hidden=false;}addEventListener(){}querySelector(){return new FakeEl()}appendChild(){}setAttribute(){}}
class FakeAudio{constructor(){this.volume=1;this.currentTime=0}addEventListener(){}play(){return Promise.resolve()}pause(){}}
class Scene{constructor(){}}
const PMath={Clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),Between:(a,b)=>Math.floor((a+b)/2),FloatBetween:(a,b)=>(a+b)/2,Distance:{Between:(a,b,c,d)=>Math.hypot(c-a,d-b),Squared:(a,b,c,d)=>(c-a)**2+(d-b)**2},Angle:{Between:(a,b,c,d)=>Math.atan2(d-b,c-a),Wrap:a=>{while(a<=-Math.PI)a+=Math.PI*2;while(a>Math.PI)a-=Math.PI*2;return a}},Linear:(a,b,t)=>a+(b-a)*t,RadToDeg:r=>r*180/Math.PI};
const ctx={console,window:{io:null,AudioContext:null,webkitAudioContext:null,location:{search:''}},document:{querySelector:()=>new FakeEl(),querySelectorAll:()=>[],createElement:()=>new FakeEl()},navigator:{clipboard:{writeText:async()=>{}}},localStorage:{getItem:()=>null,setItem(){}},Audio:FakeAudio,Image:class{},Phaser:{Scene,Math:PMath,Utils:{Array:{GetRandom:a=>a[0]}},Scale:{FIT:1,CENTER_BOTH:1},AUTO:1,Game:class{}},setTimeout,clearTimeout,Map,Set,Math,Number,Infinity};
vm.createContext(ctx);vm.runInContext(src,ctx,{filename:'game.js'});
const X=ctx.window.__TEST_EXPORTS;
let passed=0;function test(n,f){try{f();console.log('PASS',n);passed++}catch(e){console.error('FAIL',n);console.error(e.stack||e);process.exitCode=1}}
function scene(){const s=new X.SurvivorScene();s.init({character:'jjigae'});s.showBanner=()=>{};s.cameras={main:{flash(){},shake(){},width:960,height:540}};s.time={delayedCall:(ms,fn)=>({ms,fn})};return s}

test('15 minute TRUE BOSS schedule is 3/6/9/12/15',()=>assert.deepEqual(Array.from(X.TRUE_BOSS_SCHEDULE_MS),[180000,360000,540000,720000,900000]));
test('five boss order is grape choco onion coffee gum',()=>assert.deepEqual(Array.from(X.TRUE_BOSS_ORDER),['grape','choco','onion','coffee','gum']));
test('all five bosses have three visual phases and individual hurtboxes',()=>{for(const k of X.TRUE_BOSS_ORDER){const d=X.BOSS_DEFINITIONS[k];assert.equal(d.textures.length,3,k);assert.equal(d.phaseNames.length,3,k);assert(d.hurtbox.r>=27&&d.hurtbox.r<=32,k);assert(d.ultimate,k)}});
test('boss hurtbox is substantially larger than v1.16.2 25 radius',()=>{for(const k of X.TRUE_BOSS_ORDER)assert(X.BOSS_DEFINITIONS[k].hurtbox.r>25,k)});
test('all bosses have patterns in phase 1,2,3',()=>{for(const k of X.TRUE_BOSS_ORDER)for(const ph of [1,2,3])assert(X.TRUE_BOSS_PATTERNS[k].some(p=>p.phase===ph),`${k} p${ph}`)});
test('pattern execute keys exist as switch cases',()=>{const code=fs.readFileSync(gamePath,'utf8');for(const k of X.TRUE_BOSS_ORDER)for(const p of X.TRUE_BOSS_PATTERNS[k])assert(code.includes(`case '${p.execute}'`),p.execute)});
test('cleanup XP preservation is 100%',()=>assert.equal(X.HEALING.cleanupXpRatio,1));
test('v1.16.2 player and bullet honest hitboxes remain',()=>{assert.equal(X.PLAYER_SPRITES.gamja.hitbox.r,6);assert.equal(X.PLAYER_SPRITES.jjigae.hitbox.r,7);assert.equal(X.ENEMY_BULLET_HITBOX.raid.hitRadius,5.5);assert(X.ENEMY_BULLET_HITBOX.raid.hitRadius<X.ENEMY_BULLET_HITBOX.raid.visualRadius)});
test('grape rush v1.17 readable tuning preserved',()=>{assert.equal(X.GRAPE_RUSH.targetSpeed,1340);assert(X.GRAPE_RUSH.telegraphMs>=750);assert(X.GRAPE_RUSH.recoveryMs>=550)});
test('claw reaches 128px at level5 and has 8 directions',()=>{const st=X.treasureSkillStats('sword',5);assert.equal(st.reach,128);assert.equal(st.directions,8);assert(st.clearNormalBullets&&st.finisher)});
test('leash two lines share same level radius at lv3-5',()=>{for(const lv of [3,4,5]){const st=X.treasureSkillStats('hellConductor',lv);assert.equal(st.count,2);assert.equal(st.radius,st.outerRadius)}});
test('leash anchors exist per character',()=>{for(const k of ['jjigae','mandu','gamja','gucci']){const a=X.PLAYER_SPRITES[k].leashAnchor;assert(Number.isFinite(a.x)&&Number.isFinite(a.y),k)}});
test('delivery interval and reward weights are valid 45-75 sec / 100%',()=>{assert.equal(X.DELIVERY.minDelay,45000);assert.equal(X.DELIVERY.maxDelay,75000);assert.equal(X.DELIVERY.rewards.reduce((a,b)=>a+b.weight,0),100)});
test('delivery reward table exact weights',()=>assert.deepEqual(Object.fromEntries(X.DELIVERY.rewards.map(x=>[x.id,x.weight])),{snack:35,buff:25,magnet:15,weird:10,skill:10,bonk:5}));
test('init clears run/endless/delivery state',()=>{const s=scene();assert.equal(s.nextRaidIndex,0);assert.equal(s.nextRaidAt,180000);assert.equal(s.endlessMode,false);assert.equal(s.runCleared,false);assert(s.nextDeliveryAt>=45000&&s.nextDeliveryAt<=75000)});
test('pending without regular boss only blocks within 3 sec of boss start',()=>{const s=scene();s.runTimeMs=340000;s.lastRegularBossSpawnAt=300000;s.enemies={getChildren:()=>[]};s.queueTrueBossEncounter(1,1,360000);assert.equal(s.pendingTrueBoss.blockSpawns,false);assert.equal(s.updatePendingTrueBoss(),false);s.runTimeMs=357100;assert.equal(s.updatePendingTrueBoss(),true)});
test('battlefield cleanup sums live enemies and floor gems at 100%',()=>{const s=scene();s.xp=0;const mk=(role,xp)=>({active:true,enemyRole:role,xpValue:xp,x:0,y:0,getData:()=>false,destroy(){this.active=false}});const a=mk('normal',2),b=mk('elite',8),g={active:true,xpValue:3,destroy(){this.active=false}};s.enemies={getChildren:()=>[a,b]};s.gems={getChildren:()=>[g]};s.items={getChildren:()=>[]};s.enemyProjectiles={clear(){}};s.destroyEnemyDecorations=()=>{};s.clearRaidHazards=()=>{};s.dropChest=()=>{};s.dropSnack=()=>{};const old=Math.random;Math.random=()=>1;try{const r=s.clearBattlefieldForRaid();assert.equal(r.cleanupXp,13);assert.equal(s.xp,13)}finally{Math.random=old}});
test('final phase has short guard and ultimate scheduling source',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('phaseGuardUntil=phase===3?this.runTimeMs+800:0'));assert(code.includes('executeRaidUltimate(enemy)'))});
test('chocolate puddle has warning and two-stage projectile arc',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("'puddleWarning'"));assert(code.includes('duration:260'));assert(code.includes('telegraphChocoPuddle'))});
test('grape cluster requires 210px minimum split distance',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("b.splitMinDistance=type==='grape'?210:145"));assert(code.includes('splitForceAt'))});
test('run clear and endless methods exist',()=>{const s=scene();assert.equal(typeof s.showRunComplete,'function');assert.equal(typeof s.continueEndless,'function');assert.equal(typeof s.applyRemoteEndless,'function')});
test('delivery is host authoritative and personal/team rules exist',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("else if(type==='delivery'){if(this.coopMode&&this.networkRole!=='host')return"));assert(code.includes('this.maxHp*.18'));assert(code.includes('reverseControlsUntil'))});
test('persistent object caps remain',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('while(this.raidHazards.length>8)'));assert(code.includes('while((this.pawMines||[]).length>=st.maxMines)'))});

test('raid boss melee padding uses most of visible hurtbox instead of the old tiny center fraction',()=>{const s=scene();const e={x:100,y:100,enemyRole:'raidBoss',hurtboxRadius:30,scaleX:3,scaleY:3,raidKind:'grape',width:72,height:72,originX:.5,originY:.5,frame:{realWidth:72,realHeight:72}};const hc=s.enemyHurtCircle(e);assert(hc.r>=90);assert(s.meleeHurtPadding(e,.42,.88)>=79);assert(Math.abs(hc.y-6)<1e-6||Number.isFinite(hc.y))});
test('F2 raid boss debug uses actual hurt-circle helper',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('const hc=this.enemyHurtCircle(e)'));assert(code.includes('g.strokeCircle(hc.x,hc.y,hc.r)'))});
test('2P snapshots include chocolate/gum telegraphs and delivery landing warnings',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("trackTransientFx('raidTelegraphs',warn,'puddleWarning')"));assert(code.includes("trackTransientFx('raidTelegraphs',projectile,'raidChocoBig')"));assert(code.includes("trackTransientFx('deliveryWarnings',shadow,'deliveryShadow')"));assert(code.includes('(this.raidTelegraphs||[]).forEach'));assert(code.includes('(this.deliveryWarnings||[]).forEach'))});
test('delivery telegraph cancels cleanly if a TRUE BOSS transition begins during its one-second warning',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("if(this.raidBossActive||this.pendingTrueBoss||this.raidBossTransition||this.runCleared){alert.destroy();shadow.destroy();return;}"))});
test('coffee final charges then fires for about two seconds',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("enemy.ultimateChargeUntil=this.runTimeMs+800;enemy.ultimateChargeKind='coffee'"));assert(code.includes('for(let n=0;n<12;n++)this.scheduleRaidAction(enemy,800+180*n'))});
test('gum final visibly charges for about 0.9 seconds before burst',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes("enemy.ultimateChargeUntil=this.runTimeMs+900;enemy.ultimateChargeKind='gum'"));assert(code.includes('this.scheduleRaidAction(enemy,900'))});
test('2P snapshot relays Final ultimate warning names to the guest',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('raidUltimateSeq:this.raidUltimateSeq||0'));assert(code.includes('raidUltimateName:this.raidUltimateName||'));assert(code.includes('lastNetRaidUltimateSeq'));assert(code.includes("this.showBanner(s.raidUltimateName||'필살기!'"))});
test('boss numeric definitions and pattern metadata contain no NaN/Infinity inputs',()=>{for(const k of X.TRUE_BOSS_ORDER){const d=X.BOSS_DEFINITIONS[k];for(const v of [d.baseHp,d.baseSpeed,d.contactDamage,d.hurtbox.r,d.hurtbox.ox,d.hurtbox.oy])assert(Number.isFinite(v),k);for(const p of X.TRUE_BOSS_PATTERNS[k])for(const v of [p.phase,p.weight,p.cooldown,p.minDistance])assert(Number.isFinite(v),`${k}:${p.id}`)}});
test('Final phase protection covers the one-time ultimate trigger',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('phaseGuardUntil=phase===3?this.runTimeMs+800:0'));assert(code.includes("if(phase===3&&!enemy.ultimateUsed)"));assert(code.includes('enemy.ultimateUsed=true'));assert(code.includes('this.time.delayedCall(700'))});
test('Endless continuation starts a fresh five-boss cycle three minutes later',()=>{const s=scene();s.runTimeMs=901000;s.runCleared=true;s.endlessCycle=0;s.physics={world:{resume(){this.resumed=true}}};s.time={paused:true};s.continueEndless();assert.equal(s.runCleared,false);assert.equal(s.endlessMode,true);assert.equal(s.nextRaidIndex,0);assert.equal(s.nextRaidAt,1081000);assert.equal(s.endlessCycle,1)});
test('2P raid targeting has weak anti-focus weighting',()=>{const code=fs.readFileSync(gamePath,'utf8');assert(code.includes('Math.random()<0.65'));assert(code.includes('lastRaidTargetId'))});
if(process.exitCode)process.exit(process.exitCode);console.log(`ALL V1.18 LOGIC PASS (${passed})`);
